export default {
  id: "bamboo",
  name: "Garden",
  description: "Organic and natural. Earthy greens, warm paper tone, clean but warm.",
  category: "natural",
  previewColors: ["#F4F1E8", "#5A7C3A", "#2C3E2D"],
  starterSections: ["Appetizers", "Mains", "Vegetables & Sides", "Desserts"],
  colors: {
    bg: "#F4F1E8",
    text: "#2C3E2D",
    accent: "#5A7C3A",
    muted: "#7A8B6A",
    divider: "#5A7C3A33",
    heading: "#5A7C3A",
  },
  fonts: {
    title: "'Lora', serif",
    heading: "'Lora', serif",
    body: "'DM Sans', sans-serif",
    price: "'DM Sans', sans-serif",
    imports: [
      "Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500",
      "DM+Sans:wght@400;500",
    ],
  },
  sizes: { title: 32, subtitle: 12, section: 14, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 28, dishGap: 14, pagePadding: 44, headerBottom: 32, descTop: 3 },
  typography: {
    titleWeight: 400,
    titleLetterSpacing: "1px",
    titleTransform: "none",
    titleStyle: "italic",
    sectionWeight: 600,
    sectionLetterSpacing: "3px",
    sectionTransform: "uppercase",
    dishWeight: 500,
    descStyle: "normal",
  },
  layout: {
    dotLeader: true,
    dotChar: "–",
    dotColor: "#5A7C3A44",
    dividerStyle: "simple-line",
    headerDecor: "none",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  allergens: { iconSize: 12, iconColor: "#7A8B6A", position: "after-desc" },
};
