export default {
  id: "brasserie",
  name: "Brasserie",
  description: "Warm Parisian bistro. Cream bg, deep burgundy accents, classic serif typography.",
  category: "classic",
  previewColors: ["#FAF6F0", "#722F37", "#2C2420"],
  starterSections: ["Appetizers", "Mains", "Sides", "Desserts"],
  colors: {
    bg: "#FAF6F0",
    text: "#2C2420",
    accent: "#722F37",
    muted: "#8A7E74",
    divider: "#722F3733",
    heading: "#722F37",
  },
  fonts: {
    title: "'Cormorant Garamond', serif",
    heading: "'Cormorant Garamond', serif",
    body: "'EB Garamond', serif",
    price: "'EB Garamond', serif",
    imports: [
      "Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400",
      "EB+Garamond:ital,wght@0,400;0,500;1,400",
    ],
  },
  sizes: { title: 34, subtitle: 12, section: 15, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 28, dishGap: 14, pagePadding: 44, headerBottom: 32, descTop: 3 },
  typography: {
    titleWeight: 600,
    titleLetterSpacing: "2px",
    titleTransform: "uppercase",
    titleStyle: "normal",
    sectionWeight: 600,
    sectionLetterSpacing: "3px",
    sectionTransform: "uppercase",
    dishWeight: 400,
    descStyle: "italic",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#8A7E7444",
    dividerStyle: "ornamental-line",
    headerDecor: "single-rule",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  allergens: { iconSize: 12, iconColor: "#8A7E74", position: "after-desc" },
};
