export default {
  id: "coastline",
  name: "Coastline",
  description: "Mediterranean calm. White bg, soft navy and warm sand tones, airy spacing.",
  category: "natural",
  previewColors: ["#FFFFFF", "#35536E", "#C4A97D"],
  starterSections: ["Appetizers", "Seafood", "Mains", "Sides", "Desserts"],
  colors: {
    bg: "#FFFFFF",
    text: "#2A3540",
    accent: "#35536E",
    muted: "#8C9AA6",
    divider: "#35536E22",
    heading: "#35536E",
  },
  fonts: {
    title: "'DM Serif Display', serif",
    heading: "'DM Serif Display', serif",
    body: "'Source Sans 3', sans-serif",
    price: "'Source Sans 3', sans-serif",
    imports: [
      "DM+Serif+Display:ital@0;1",
      "Source+Sans+3:ital,wght@0,300;0,400;0,500;0,600;1,400",
    ],
  },
  sizes: { title: 34, subtitle: 12, section: 16, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 30, dishGap: 14, pagePadding: 44, headerBottom: 34, descTop: 3 },
  typography: {
    titleWeight: 400,
    titleLetterSpacing: "2px",
    titleTransform: "none",
    titleStyle: "normal",
    sectionWeight: 400,
    sectionLetterSpacing: "2px",
    sectionTransform: "uppercase",
    dishWeight: 500,
    descStyle: "normal",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#8C9AA644",
    dividerStyle: "simple-line",
    headerDecor: "underline",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  allergens: { iconSize: 12, iconColor: "#8C9AA6", position: "after-desc" },
};
