export default {
  id: "copperplate",
  name: "Copperplate",
  description: "Art deco inspired. Dark charcoal bg, warm copper accents, geometric elegance.",
  category: "formal",
  previewColors: ["#1C1C1E", "#C08B5C", "#E8DFD0"],
  starterSections: ["Starters", "Mains", "Sides", "Desserts"],
  colors: {
    bg: "#1C1C1E",
    text: "#E8DFD0",
    accent: "#C08B5C",
    muted: "#9A8E80",
    divider: "#C08B5C33",
    heading: "#C08B5C",
  },
  fonts: {
    title: "'Cinzel', serif",
    heading: "'Cinzel', serif",
    body: "'Raleway', sans-serif",
    price: "'Raleway', sans-serif",
    imports: [
      "Cinzel:wght@400;500;600;700",
      "Raleway:ital,wght@0,300;0,400;0,500;1,400",
    ],
  },
  sizes: { title: 32, subtitle: 11, section: 15, dish: 14, desc: 12, price: 14 },
  spacing: { sectionGap: 30, dishGap: 14, pagePadding: 46, headerBottom: 36, descTop: 3 },
  typography: {
    titleWeight: 600,
    titleLetterSpacing: "4px",
    titleTransform: "uppercase",
    titleStyle: "normal",
    sectionWeight: 500,
    sectionLetterSpacing: "4px",
    sectionTransform: "uppercase",
    dishWeight: 400,
    descStyle: "italic",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#C08B5C33",
    dividerStyle: "ornamental-line",
    headerDecor: "double-rule",
    border: "solid 1px #C08B5C33",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  logo: { width: 60, height: 60, shape: "circle" },
  allergens: { iconSize: 12, iconColor: "#9A8E80", position: "after-desc" },
};
