export default {
  id: "copperplate",
  name: "Deco",
  description: "Art deco boldness. Dark charcoal bg, warm copper, geometric display type.",
  category: "formal",
  previewColors: ["#1C1C1E", "#C08B5C", "#E8DFD0"],
  starterSections: ["Starters", "Mains", "Sides", "Desserts"],
  colors: {
    bg: "#1C1C1E",
    text: "#E8DFD0",
    accent: "#C08B5C",
    muted: "#9A8E80",
    divider: "#C08B5C33",
    heading: "#C08B5C",
  },
  fonts: {
    title: "'Abril Fatface', serif",
    heading: "'Josefin Sans', sans-serif",
    body: "'Raleway', sans-serif",
    price: "'Raleway', sans-serif",
    imports: [
      "Abril+Fatface",
      "Josefin+Sans:wght@300;400;500;600",
      "Raleway:ital,wght@0,300;0,400;0,500;1,400",
    ],
  },
  sizes: { title: 38, subtitle: 10, section: 12, dish: 14, desc: 11, price: 14 },
  spacing: { sectionGap: 28, dishGap: 12, pagePadding: 46, headerBottom: 36, descTop: 3 },
  typography: {
    titleWeight: 400,
    titleLetterSpacing: "3px",
    titleTransform: "none",
    titleStyle: "normal",
    sectionWeight: 400,
    sectionLetterSpacing: "5px",
    sectionTransform: "uppercase",
    dishWeight: 400,
    descStyle: "normal",
  },
  layout: {
    dotLeader: false,
    dotChar: " ",
    dotColor: "transparent",
    dividerStyle: "left-accent",
    headerDecor: "double-rule",
    border: "solid 1px #C08B5C33",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "left",
  },
  logo: { width: 60, height: 60, shape: "circle" },
  allergens: { iconSize: 12, iconColor: "#9A8E80", position: "after-desc" },
};
