export default {
  id: "ink-steam",
  name: "Blanc",
  description: "Minimalist restraint. Maximum whitespace, dramatic simplicity.",
  category: "minimal",
  previewColors: ["#FAFAF8", "#1A1A1A", "#999999"],
  starterSections: ["To Start", "Mains", "Sides", "Desserts"],
  colors: {
    bg: "#FAFAF8",
    text: "#1A1A1A",
    accent: "#1A1A1A",
    muted: "#999999",
    divider: "#1A1A1A22",
    heading: "#1A1A1A",
  },
  fonts: {
    title: "'Josefin Sans', sans-serif",
    heading: "'Josefin Sans', sans-serif",
    body: "'DM Sans', sans-serif",
    price: "'DM Sans', sans-serif",
    imports: [
      "Josefin+Sans:wght@300;400;500",
      "DM+Sans:wght@400;500",
    ],
  },
  sizes: { title: 42, subtitle: 11, section: 11, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 40, dishGap: 14, pagePadding: 50, headerBottom: 40, descTop: 3 },
  typography: {
    titleWeight: 300,
    titleLetterSpacing: "6px",
    titleTransform: "uppercase",
    sectionWeight: 500,
    sectionLetterSpacing: "5px",
    sectionTransform: "uppercase",
    dishWeight: 500,
    descStyle: "normal",
  },
  layout: {
    dotLeader: false,
    dotChar: " ",
    dotColor: "transparent",
    dividerStyle: "none",
    headerDecor: "single-rule",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  allergens: { iconSize: 12, iconColor: "#999999", position: "after-desc" },
};
