export default {
  id: "jade-palace",
  name: "Evergreen",
  description: "Formal elegance. Deep jade bg, warm gold accents, ornamental dividers.",
  category: "formal",
  previewColors: ["#0C2E1F", "#D4A54A", "#F0E6D0"],
  starterSections: ["Appetizers", "Soups", "Mains", "Sides", "Desserts"],
  colors: {
    bg: "#0C2E1F",
    text: "#F0E6D0",
    accent: "#D4A54A",
    muted: "#A89878",
    divider: "#D4A54A33",
    heading: "#D4A54A",
  },
  fonts: {
    title: "'Cinzel', serif",
    heading: "'Cinzel', serif",
    body: "'Cormorant Garamond', serif",
    price: "'Cormorant Garamond', serif",
    imports: [
      "Cinzel:wght@400;500;600;700",
      "Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400",
    ],
  },
  sizes: { title: 34, subtitle: 12, section: 17, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 30, dishGap: 14, pagePadding: 46, headerBottom: 36, descTop: 3 },
  typography: {
    titleWeight: 700,
    titleLetterSpacing: "3px",
    titleTransform: "uppercase",
    sectionWeight: 500,
    sectionLetterSpacing: "4px",
    sectionTransform: "uppercase",
    dishWeight: 600,
    descStyle: "italic",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#D4A54A44",
    dividerStyle: "ornamental-line",
    headerDecor: "double-rule",
    border: "solid 1px #D4A54A33",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  logo: { width: 70, height: 70, shape: "circle" },
  allergens: { iconSize: 12, iconColor: "#A89878", position: "after-desc" },
};
