export default {
  id: "midnight-market",
  name: "Gilded Dark",
  description: "Upscale luxe. Near-black bg with warm gold. Luxe but approachable.",
  category: "formal",
  previewColors: ["#111111", "#C9A84C", "#E8DCC8"],
  starterSections: ["Starters", "Mains", "Sides", "Desserts & Drinks"],
  colors: {
    bg: "#111111",
    text: "#E8DCC8",
    accent: "#C9A84C",
    muted: "#9B8E78",
    divider: "#C9A84C33",
    heading: "#C9A84C",
  },
  fonts: {
    title: "'Cinzel Decorative', serif",
    heading: "'EB Garamond', serif",
    body: "'EB Garamond', serif",
    price: "'EB Garamond', serif",
    imports: [
      "Cinzel+Decorative:wght@400;700",
      "EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400",
    ],
  },
  sizes: { title: 30, subtitle: 12, section: 15, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 30, dishGap: 14, pagePadding: 46, headerBottom: 36, descTop: 3 },
  typography: {
    titleWeight: 400,
    titleLetterSpacing: "4px",
    titleTransform: "uppercase",
    sectionWeight: 500,
    sectionLetterSpacing: "3px",
    sectionTransform: "uppercase",
    dishWeight: 500,
    descStyle: "italic",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#C9A84C44",
    dividerStyle: "ornamental-line",
    headerDecor: "ornament-row",
    border: "solid 1px #C9A84C33",
    outerBorder: "none",
    borderInset: 4,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  logo: { width: 70, height: 70, shape: "circle" },
  allergens: { iconSize: 12, iconColor: "#9B8E78", position: "after-desc" },
};
