export default {
  id: "midnight-market",
  name: "Sterling",
  description: "Cool luxury. Deep navy bg, silver accents, high-contrast modern serif.",
  category: "formal",
  previewColors: ["#0F1923", "#A8B8C8", "#E2E8EE"],
  starterSections: ["Starters", "Mains", "Sides", "Desserts & Drinks"],
  colors: {
    bg: "#0F1923",
    text: "#E2E8EE",
    accent: "#A8B8C8",
    muted: "#7088A0",
    divider: "#A8B8C833",
    heading: "#A8B8C8",
  },
  fonts: {
    title: "'Bodoni Moda', serif",
    heading: "'Bodoni Moda', serif",
    body: "'Source Serif 4', serif",
    price: "'Source Serif 4', serif",
    imports: [
      "Bodoni+Moda:ital,wght@0,400;0,500;0,600;0,700;1,400",
      "Source+Serif+4:ital,wght@0,400;0,500;0,600;1,400",
    ],
  },
  sizes: { title: 36, subtitle: 11, section: 13, dish: 14, desc: 11, price: 14 },
  spacing: { sectionGap: 34, dishGap: 16, pagePadding: 50, headerBottom: 40, descTop: 4 },
  typography: {
    titleWeight: 500,
    titleLetterSpacing: "5px",
    titleTransform: "uppercase",
    sectionWeight: 500,
    sectionLetterSpacing: "4px",
    sectionTransform: "uppercase",
    dishWeight: 400,
    descStyle: "italic",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#A8B8C833",
    dividerStyle: "simple-line",
    headerDecor: "underline",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  logo: { width: 70, height: 70, shape: "circle" },
  allergens: { iconSize: 12, iconColor: "#7088A0", position: "after-desc" },
};
