export default {
  id: "modernist",
  name: "Modernist",
  description: "Typography-forward. Clean white bg, stark black text, Swiss-style precision.",
  category: "minimal",
  previewColors: ["#FFFFFF", "#111111", "#777777"],
  starterSections: ["To Start", "Mains", "Sides", "Desserts"],
  colors: {
    bg: "#FFFFFF",
    text: "#111111",
    accent: "#111111",
    muted: "#777777",
    divider: "#11111118",
    heading: "#111111",
  },
  fonts: {
    title: "'Inter', sans-serif",
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
    price: "'Inter', sans-serif",
    imports: [
      "Inter:wght@300;400;500;600;700",
    ],
  },
  sizes: { title: 28, subtitle: 10, section: 12, dish: 14, desc: 12, price: 14 },
  spacing: { sectionGap: 28, dishGap: 12, pagePadding: 40, headerBottom: 30, descTop: 3 },
  typography: {
    titleWeight: 700,
    titleLetterSpacing: "6px",
    titleTransform: "uppercase",
    titleStyle: "normal",
    sectionWeight: 600,
    sectionLetterSpacing: "4px",
    sectionTransform: "uppercase",
    dishWeight: 400,
    descStyle: "normal",
  },
  layout: {
    dotLeader: true,
    dotChar: " ",
    dotColor: "#11111118",
    dividerStyle: "none",
    headerDecor: "top-rule",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "left",
  },
  allergens: { iconSize: 12, iconColor: "#777777", position: "after-desc" },
};
