export default {
  id: "porcelain",
  name: "Porcelain",
  description: "Chinese blue-and-white pottery. Clean white bg, rich blue accents. Delicate and refined.",
  category: "asian",
  previewColors: ["#FFFFFF", "#2B5BA3", "#1A2744"],
  starterSections: ["Appetizers", "Seafood", "Poultry & Meat", "Vegetables & Tofu", "Noodles & Rice", "Desserts"],
  colors: {
    bg: "#FFFFFF",
    text: "#1A2744",
    accent: "#2B5BA3",
    muted: "#7889A0",
    divider: "#2B5BA333",
    heading: "#2B5BA3",
  },
  fonts: {
    title: "'Playfair Display', serif",
    heading: "'Playfair Display', serif",
    body: "'Cormorant Garamond', serif",
    price: "'Cormorant Garamond', serif",
    imports: [
      "Playfair+Display:wght@400;500;600;700",
      "Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400",
    ],
  },
  sizes: { title: 34, subtitle: 12, section: 15, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 30, dishGap: 14, pagePadding: 46, headerBottom: 36, descTop: 3 },
  typography: {
    titleWeight: 700,
    titleLetterSpacing: "3px",
    titleTransform: "uppercase",
    sectionWeight: 600,
    sectionLetterSpacing: "3px",
    sectionTransform: "uppercase",
    dishWeight: 500,
    descStyle: "italic",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#2B5BA344",
    dividerStyle: "line-through",
    headerDecor: "dots-and-rule",
    border: "double 3px #2B5BA344",
    outerBorder: "none",
    borderInset: 6,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  allergens: { iconSize: 12, iconColor: "#7889A0", position: "after-desc" },
};
