export default {
  id: "red-lantern",
  name: "Broadsheet",
  description: "Confident editorial. Rich red accents, serif/sans contrast, modern layout.",
  category: "classic",
  previewColors: ["#FBF5EC", "#B82025", "#1C1C1C"],
  starterSections: ["Small Plates", "Large Plates", "Sides", "Drinks"],
  colors: {
    bg: "#FBF5EC",
    text: "#1C1C1C",
    accent: "#B82025",
    muted: "#6B5E4F",
    divider: "#B8202533",
    heading: "#B82025",
  },
  fonts: {
    title: "'Playfair Display', serif",
    heading: "'Work Sans', sans-serif",
    body: "'Work Sans', sans-serif",
    price: "'Work Sans', sans-serif",
    imports: [
      "Playfair+Display:wght@700;800;900",
      "Work+Sans:ital,wght@0,300;0,400;0,500;0,600;1,400",
    ],
  },
  sizes: { title: 36, subtitle: 12, section: 12, dish: 14, desc: 12, price: 14 },
  spacing: { sectionGap: 30, dishGap: 14, pagePadding: 44, headerBottom: 34, descTop: 3 },
  typography: {
    titleWeight: 800,
    titleLetterSpacing: "2px",
    titleTransform: "uppercase",
    sectionWeight: 600,
    sectionLetterSpacing: "4px",
    sectionTransform: "uppercase",
    dishWeight: 400,
    descStyle: "normal",
  },
  layout: {
    dotLeader: false,
    dotChar: " ",
    dotColor: "transparent",
    dividerStyle: "neon-bar",
    headerDecor: "block-accent",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "left",
  },
  logo: { width: 80, height: 60, shape: "rect" },
  allergens: { iconSize: 12, iconColor: "#6B5E4F", position: "after-desc" },
};
