export default {
  id: "red-lantern",
  name: "Bold Serif",
  description: "Confident and bold. Rich red, cream bg, strong serif typography.",
  category: "classic",
  previewColors: ["#FBF5EC", "#B82025", "#1C1C1C"],
  starterSections: ["Small Plates", "Large Plates", "Sides", "Drinks"],
  colors: {
    bg: "#FBF5EC",
    text: "#1C1C1C",
    accent: "#B82025",
    muted: "#6B5E4F",
    divider: "#B8202533",
    heading: "#B82025",
  },
  fonts: {
    title: "'Playfair Display', serif",
    heading: "'Libre Baskerville', serif",
    body: "'Libre Baskerville', serif",
    price: "'Libre Baskerville', serif",
    imports: [
      "Playfair+Display:wght@700;800;900",
      "Libre+Baskerville:ital,wght@0,400;0,700;1,400",
    ],
  },
  sizes: { title: 36, subtitle: 12, section: 14, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 30, dishGap: 14, pagePadding: 44, headerBottom: 34, descTop: 3 },
  typography: {
    titleWeight: 800,
    titleLetterSpacing: "2px",
    titleTransform: "uppercase",
    sectionWeight: 700,
    sectionLetterSpacing: "3px",
    sectionTransform: "uppercase",
    dishWeight: 400,
    descStyle: "italic",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#6B5E4F66",
    dividerStyle: "thick-rule",
    headerDecor: "block-accent",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  logo: { width: 80, height: 60, shape: "rect" },
  allergens: { iconSize: 12, iconColor: "#6B5E4F", position: "after-desc" },
};
