export default {
  id: "silk-road",
  name: "Silk Road",
  description: "Pan-Asian modern editorial. Warm spice tones. Magazine layout influence.",
  category: "fusion",
  previewColors: ["#FAF4EC", "#C45D2C", "#2A1F17"],
  starterSections: ["To Begin", "Curries & Braises", "From the Grill", "Grains & Noodles", "To Finish"],
  colors: {
    bg: "#FAF4EC",
    text: "#2A1F17",
    accent: "#C45D2C",
    muted: "#8B7562",
    divider: "#2A1F1733",
    heading: "#2A1F17",
  },
  fonts: {
    title: "'Playfair Display', serif",
    heading: "'Lora', serif",
    body: "'DM Sans', sans-serif",
    price: "'DM Sans', sans-serif",
    imports: [
      "Playfair+Display:ital,wght@0,700;0,800;1,700;1,800",
      "Lora:wght@400;500;600",
      "DM+Sans:wght@400;500",
    ],
  },
  sizes: { title: 38, subtitle: 12, section: 13, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 30, dishGap: 14, pagePadding: 44, headerBottom: 34, descTop: 3 },
  typography: {
    titleWeight: 800,
    titleLetterSpacing: "1px",
    titleTransform: "none",
    titleStyle: "italic",
    sectionWeight: 500,
    sectionLetterSpacing: "3px",
    sectionTransform: "uppercase",
    dishWeight: 500,
    descStyle: "normal",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#8B756244",
    dividerStyle: "thick-rule",
    headerDecor: "top-rule",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "left",
  },
  allergens: { iconSize: 12, iconColor: "#8B7562", position: "after-desc" },
};
