export default {
  id: "tea-house",
  name: "Quiet Craft",
  description: "Serene and understated. Warm earth tones, generous breathing room.",
  category: "minimal",
  previewColors: ["#F7F3EB", "#8C6D46", "#3D352B"],
  starterSections: ["Light Bites", "Mains", "Sides", "Sweets"],
  colors: {
    bg: "#F7F3EB",
    text: "#3D352B",
    accent: "#8C6D46",
    muted: "#A0927E",
    divider: "#8C6D4633",
    heading: "#8C6D46",
  },
  fonts: {
    title: "'EB Garamond', serif",
    heading: "'EB Garamond', serif",
    body: "'EB Garamond', serif",
    price: "'EB Garamond', serif",
    imports: [
      "EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500",
    ],
  },
  sizes: { title: 32, subtitle: 11, section: 14, dish: 15, desc: 11, price: 15 },
  spacing: { sectionGap: 36, dishGap: 16, pagePadding: 48, headerBottom: 38, descTop: 4 },
  typography: {
    titleWeight: 600,
    titleLetterSpacing: "2px",
    titleTransform: "uppercase",
    sectionWeight: 500,
    sectionLetterSpacing: "4px",
    sectionTransform: "uppercase",
    dishWeight: 500,
    descStyle: "italic",
  },
  layout: {
    dotLeader: true,
    dotChar: "·",
    dotColor: "#8C6D4644",
    dividerStyle: "circle-line",
    headerDecor: "single-rule",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "center",
  },
  allergens: { iconSize: 12, iconColor: "#A0927E", position: "after-desc" },
};
