export default {
  id: "tea-house",
  name: "Linen",
  description: "Serene and spacious. Warm earth tones, generous whitespace, unhurried feel.",
  category: "minimal",
  previewColors: ["#F7F3EB", "#8C6D46", "#3D352B"],
  starterSections: ["Light Bites", "Mains", "Sides", "Sweets"],
  colors: {
    bg: "#F7F3EB",
    text: "#3D352B",
    accent: "#8C6D46",
    muted: "#A0927E",
    divider: "#8C6D4622",
    heading: "#3D352B",
  },
  fonts: {
    title: "'Spectral', serif",
    heading: "'Spectral', serif",
    body: "'Karla', sans-serif",
    price: "'Karla', sans-serif",
    imports: [
      "Spectral:ital,wght@0,300;0,400;0,500;0,600;1,400",
      "Karla:ital,wght@0,300;0,400;0,500;1,400",
    ],
  },
  sizes: { title: 30, subtitle: 10, section: 11, dish: 14, desc: 11, price: 14 },
  spacing: { sectionGap: 40, dishGap: 18, pagePadding: 52, headerBottom: 44, descTop: 5 },
  typography: {
    titleWeight: 300,
    titleLetterSpacing: "5px",
    titleTransform: "uppercase",
    sectionWeight: 500,
    sectionLetterSpacing: "6px",
    sectionTransform: "uppercase",
    dishWeight: 400,
    descStyle: "italic",
  },
  layout: {
    dotLeader: false,
    dotChar: " ",
    dotColor: "transparent",
    dividerStyle: "none",
    headerDecor: "none",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "left",
  },
  allergens: { iconSize: 12, iconColor: "#A0927E", position: "after-desc" },
};
