export default {
  id: "wok-fire",
  name: "Ember",
  description: "Energetic and warm. Charcoal bg, bright orange/amber heat. Punchy and bold.",
  category: "modern",
  previewColors: ["#1E1E1E", "#E8722A", "#F5F0E8"],
  starterSections: ["Small Plates", "Grilled", "Mains", "Sides", "Desserts"],
  colors: {
    bg: "#1E1E1E",
    text: "#F5F0E8",
    accent: "#E8722A",
    muted: "#B0A898",
    divider: "#E8722A33",
    heading: "#E8722A",
  },
  fonts: {
    title: "'Josefin Sans', sans-serif",
    heading: "'Josefin Sans', sans-serif",
    body: "'DM Sans', sans-serif",
    price: "'DM Sans', sans-serif",
    imports: [
      "Josefin+Sans:wght@400;500;600;700",
      "DM+Sans:wght@400;500",
    ],
  },
  sizes: { title: 36, subtitle: 12, section: 18, dish: 15, desc: 12, price: 15 },
  spacing: { sectionGap: 28, dishGap: 14, pagePadding: 40, headerBottom: 30, descTop: 3 },
  typography: {
    titleWeight: 700,
    titleLetterSpacing: "4px",
    titleTransform: "uppercase",
    sectionWeight: 700,
    sectionLetterSpacing: "4px",
    sectionTransform: "uppercase",
    dishWeight: 500,
    descStyle: "normal",
  },
  layout: {
    dotLeader: false,
    dotChar: " ",
    dotColor: "transparent",
    dividerStyle: "left-accent",
    headerDecor: "underline",
    border: "none",
    outerBorder: "none",
    borderInset: 0,
    priceAlignment: "right",
    sectionAlignment: "left",
  },
  allergens: { iconSize: 12, iconColor: "#B0A898", position: "after-desc" },
};
